### ISSUE TITLE
Add all urls 

### ISSUE THREAD

**Issue by AlishahMughal123** [yunemse48/403bypasser#2]
Hey mate ,
add all urls list at once so it`s easy to do on all URLS.
cat urls.txt | ./bypass_403.sh

**Comment by yunemse48** [comment]
Hi bro, 

Since I'm too busy, I could barely find spare time to work on this but I did some edits (not committed yet). By thinking from your point of view, an idea came to my mind. The tool may take URLs and paths as lists. However, it becomes harder to parse and display the results in an understandable manner.

**Comment by yunemse48** [comment]
So I need some more time :) Thanks for your feedback and patience.

**Comment by yunemse48** [comment]
Hi @AlishahMughal123 ,

I've added the feature you requested by passing inputs through arguments. Could you please check it?

Thanks.
